# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2.0
blocks:
  - alignment: left
    newline: true
    segments:
    - type: os
      background: "#d75f00"
      foreground: "#f2f3f8"
      leading_diamond: "\u256d\u2500\ue0b2"
      # trailing_diamond: "\ue0b0"
      properties:
        alpine: "\uf300"
        arch: "\uf303"
        centos: "\uf304"
        debian: "\uf306"
        elementary: "\uf309"
        fedora: "\uf30a"
        gentoo: "\uf30d"
        linux: "\ue712"
        macos: "\ue711"
        manjaro: "\uf312"
        mint: "\uf30f"
        opensuse: "\uf314"
        raspbian: "\uf315"
        ubuntu: "\uf31c"
        windows: "\ue70f"
      style: diamond
      template:  "{{ .Icon }}  "

    - type: python
      style: powerline
      powerline_symbol: "\ue0b0"
      foreground: "#100e23"
      background: "#906cff"
      template: "{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{else}}{{ end }}{{ end }}"

    - type: session
      background: "#e4e4e4"
      foreground: "#4e4e4e"
      powerline_symbol: "\ue0b0"
      style: accordion
      template: "{{if (lt (add (len .UserName) 1 (len .HostName)) (atoi .Env.R_COLS))}} {{.UserName}}@{{.HostName}} {{else}} {{end}}"
    
    - type: path
      background: "#0087af"
      foreground: "#f2f3f8"
      powerline_symbol: "\ue0b0"
      properties:
        style: mixed
        folder_icon: "\u2026"
        folder_separator_icon: " <transparent>\ue0b1</> "
        mixed_threshold: 7
      style: accordion
      templates_logic: first_match
      templates:
        - "{{if lt (len .Path) (int (div .Env.COLS 2))}} {{.Path}} {{end}}"
        - "{{$p1:=cat \" \u2026 <transparent>\ue0b1</>\" (trim (trimAll \">\" (last (splitList \"/\" .Path))))}}{{if lt (len $p1) (int (mul 5 (div .Env.COLS 7))) }}{{- $p1 -}}{{else}} {{end}}"
    
    - type: git
      background: "#378504"
      background_templates:
      - "{{ if or (.Working.Changed) (.Staging.Changed) }}#a97400{{ end }}"
      - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#54433a{{ end }}"
      - "{{ if gt .Ahead 0 }}#744d89{{ end }}"
      - "{{ if gt .Behind 0 }}#744d89{{ end }}"
      foreground: "#f2f3f8"
      leading_diamond: "<transparent,background>\ue0b0</>"
      trailing_diamond: "\ue0b0"
      properties:
        branch_gone_icon: 
        branch_icon: " \uf418 "
        branch_identical_icon: "\uf444"
        branch_max_length: 25.0
        fetch_stash_count: true
        fetch_status: true
      style: diamond
      templates: 
        - "{{if (lt (len .HEAD) (atoi .Env.R_COLS))}}{{ .HEAD }}{{else}} {{trunc 7 (last (splitList \"/\" .HEAD))}}{{end}}"
        - "{{if .BranchStatus }} {{ .BranchStatus }} {{ end }}"
        - "{{ if .Working.Changed }} <transparent>\ue0b1</> <#121318>\uf044 {{ .Working.String }}</>{{ end }}"
        - "{{ if .Staging.Changed }} <transparent>\ue0b1</> <#121318>\uf046 {{ .Staging.String }}</>{{ end }}"
        - "{{ if gt .StashCount 0 }} <transparent>\ue0b1</> <#121318>󰘓 {{ .StashCount }}</>{{ end }} "
    type: prompt
  
  - alignment: right
    segments:
      - type: executiontime
        background: "#e4e4e4"
        foreground: "#585858"
        invert_powerline: true
        powerline_symbol: "\ue0b2"
        properties:
          always_enabled: true
          style: austin
        style: powerline
        template: "{{if (lt (len .FormattedMs) (atoi .Env.R_COLS))}} 󰔛 {{ .FormattedMs }} {{else}} {{end}}"
      
      - type: time
        background: "#d75f00"
        foreground: "#f2f3f8"
        invert_powerline: true
        properties:
          time_format: "15:04:05"
        style: diamond
        template: "{{if (lt (len (.CurrentDate | date .Format)) (atoi .Env.R_COLS))}} 󰃰 {{ .CurrentDate | date .Format }} {{else}} {{end}}"
        trailing_diamond: "\ue0b0"
    type: prompt
  
  - alignment: left
    newline: true
    segments:
        
        - type: text
          foreground: "#d75f00"
          style: plain
          template: "\u2570\u2500 {{ if .Root }}#{{else}}${{end}}"
    type: prompt


